// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package core

import (
	"encoding/json"
	"errors"

	"github.com/ethereum/go-ethereum/common"
)

var _ = (*genesisGovernanceMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (g GovernanceAccount) MarshalJSON() ([]byte, error) {
	type GovernanceAccount struct {
		Signer common.UnprefixedAddress `json:"signer" gencodec:"required"`
	}
	var enc GovernanceAccount
	enc.Signer = common.UnprefixedAddress(g.Signer)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (g *GovernanceAccount) UnmarshalJSON(input []byte) error {
	type GovernanceAccount struct {
		Signer *common.UnprefixedAddress `json:"signer" gencodec:"required"`
	}
	var dec GovernanceAccount
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Signer == nil {
		return errors.New("missing required field 'signer' for GovernanceAccount")
	}
	g.Signer = common.Address(*dec.Signer)
	return nil
}
